name: Frontend CI
on: [push, pull_request]

jobs:
  BUILD_GENERATE:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: npm install
        working-directory: frontend
      - run: npm run build --if-present
        working-directory: frontend
      - run: npm run generate
        working-directory: frontend
